### ISSUE TITLE
候选框的最后一个候选词长度和其他候选词长度不一致

### ISSUE THREAD

**Issue by BigOldTree** [fxliang/weasel#6]
![image](https://user-images.githubusercontent.com/95293685/224971083-bb6f861a-0827-4d2e-a27c-11a4074b463b.png)

**Comment by BigOldTree** [comment]
有没有解决方法还是哪里配置的问题

**Comment by fxliang** [comment]
已确认问题并已修复。见[CI产出](https://github.com/fxliang/weasel/actions/runs/4416805369)
![image](https://user-images.githubusercontent.com/4023160/225035119-64605881-bac6-42a1-97cd-8d7d54d0b2e6.png)
